<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PrisonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('prisons')->insert([
            [
                'id' => 1,
                'state_id' => 24,
                'prison_name' => "Max. Sec.\nKirikiri",
                'address' => '',
                'capacity' => '1056',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 2,
                'state_id' => 24,
                'prison_name' => "Med. Sec.\nKirikiri",
                'address' => '',
                'capacity' => '1700',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 3,
                'state_id' => 24,
                'prison_name' => 'Female',
                'address' => '',
                'capacity' => '211',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 4,
                'state_id' => 24,
                'prison_name' => 'Ikoyi',
                'address' => '',
                'capacity' => '800',
                'active' => 1,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 5,
                'state_id' => 24,
                'prison_name' => 'Badagry',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 6,
                'state_id' => 27,
                'prison_name' => 'Abeokuta',
                'address' => '',
                'capacity' => '510',
                'active' => 1,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 7,
                'state_id' => 27,
                'prison_name' => 'Ijebu-Ode',
                'address' => '',
                'capacity' => '322',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 8,
                'state_id' => 27,
                'prison_name' => 'Ilaro',
                'address' => '',
                'capacity' => '126',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 9,
                'state_id' => 27,
                'prison_name' => 'Shagamu',
                'address' => '',
                'capacity' => '88',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 10,
                'state_id' => 27,
                'prison_name' => 'Borstal',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 11,
                'state_id' => 27,
                'prison_name' => 'New MSP Abeokuta',
                'address' => '',
                'capacity' => '712',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 12,
                'state_id' => 27,
                'prison_name' => 'Ago-Iwoye FC',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 13,
                'state_id' => 18,
                'prison_name' => 'Birnin Gwari',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 14,
                'state_id' => 18,
                'prison_name' => 'Kaduna',
                'address' => '',
                'capacity' => '547',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 15,
                'state_id' => 18,
                'prison_name' => 'Kafanchan',
                'address' => '',
                'capacity' => '110',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 16,
                'state_id' => 18,
                'prison_name' => "Kakuri Prison \nCamp",
                'address' => '',
                'capacity' => '445',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 17,
                'state_id' => 18,
                'prison_name' => 'Zaria',
                'address' => '',
                'capacity' => '377',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 18,
                'state_id' => 18,
                'prison_name' => 'Kujama Farm',
                'address' => '',
                'capacity' => '350',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 19,
                'state_id' => 18,
                'prison_name' => 'Borstal',
                'address' => '',
                'capacity' => '208',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 20,
                'state_id' => 18,
                'prison_name' => 'Kachia Satellite',
                'address' => '',
                'capacity' => '70',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 21,
                'state_id' => 18,
                'prison_name' => 'Saminaka Satellite',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 22,
                'state_id' => 18,
                'prison_name' => 'Soba Satellite',
                'address' => '',
                'capacity' => '82',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 23,
                'state_id' => 18,
                'prison_name' => 'Manchok Satellite',
                'address' => '',
                'capacity' => '70',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 24,
                'state_id' => 18,
                'prison_name' => 'Gwantu Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 25,
                'state_id' => 18,
                'prison_name' => 'Kwoi Satellite',
                'address' => '',
                'capacity' => '70',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 26,
                'state_id' => 18,
                'prison_name' => 'Ikara Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 27,
                'state_id' => 18,
                'prison_name' => 'Makarfi Satellite',
                'address' => '',
                'capacity' => '196',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 29,
                'state_id' => 20,
                'prison_name' => 'Daura Old',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 30,
                'state_id' => 20,
                'prison_name' => 'Katsina',
                'address' => '',
                'capacity' => '237',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 31,
                'state_id' => 20,
                'prison_name' => 'MSP Funtua',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 32,
                'state_id' => 20,
                'prison_name' => 'Dutsinma Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 33,
                'state_id' => 20,
                'prison_name' => 'Kankia Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 34,
                'state_id' => 20,
                'prison_name' => "Malumfashi \nSatellite",
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 35,
                'state_id' => 20,
                'prison_name' => 'Jibia Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 36,
                'state_id' => 20,
                'prison_name' => 'Mani Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 37,
                'state_id' => 20,
                'prison_name' => 'Musawa Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 38,
                'state_id' => 20,
                'prison_name' => 'Ingawa Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 39,
                'state_id' => 17,
                'prison_name' => 'Hadejia New',
                'address' => '',
                'capacity' => '640',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 40,
                'state_id' => 17,
                'prison_name' => 'Kazaure',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 41,
                'state_id' => 17,
                'prison_name' => 'Gumel',
                'address' => '',
                'capacity' => '750',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 42,
                'state_id' => 17,
                'prison_name' => 'Birnin Kudu Farm',
                'address' => '',
                'capacity' => '300',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 43,
                'state_id' => 17,
                'prison_name' => "Birnin Kudu \nSatellite",
                'address' => '',
                'capacity' => '146',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 44,
                'state_id' => 17,
                'prison_name' => 'Gwaram Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 45,
                'state_id' => 17,
                'prison_name' => 'Dutse Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 46,
                'state_id' => 17,
                'prison_name' => 'Ringim Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 47,
                'state_id' => 17,
                'prison_name' => 'Jahum Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 48,
                'state_id' => 17,
                'prison_name' => 'Garki-Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 49,
                'state_id' => 17,
                'prison_name' => 'Kiyawa satelite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 50,
                'state_id' => 19,
                'prison_name' => 'Goron Dutse',
                'address' => '',
                'capacity' => '734',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 51,
                'state_id' => 19,
                'prison_name' => 'Kano Central',
                'address' => '',
                'capacity' => '1310',
                'active' => 1,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 52,
                'state_id' => 19,
                'prison_name' => 'Wudil',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 53,
                'state_id' => 19,
                'prison_name' => "Gwarzo \nNew Satellite",
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 54,
                'state_id' => 19,
                'prison_name' => 'Bichi Satellite',
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 55,
                'state_id' => 19,
                'prison_name' => 'Rano Satellite',
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 56,
                'state_id' => 19,
                'prison_name' => "Tudun \nWada Satellite",
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 57,
                'state_id' => 19,
                'prison_name' => 'Sumaila Satellite',
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 58,
                'state_id' => 19,
                'prison_name' => 'Kiru Satellite',
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 59,
                'state_id' => 19,
                'prison_name' => "Dawakin \nTofa Satellite",
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 60,
                'state_id' => 5,
                'prison_name' => 'Bauchi',
                'address' => '',
                'capacity' => '500',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 61,
                'state_id' => 5,
                'prison_name' => 'Azare',
                'address' => '',
                'capacity' => '151',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 62,
                'state_id' => 5,
                'prison_name' => 'Misau',
                'address' => '',
                'capacity' => '120',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 63,
                'state_id' => 5,
                'prison_name' => 'Ningi',
                'address' => '',
                'capacity' => '110',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 64,
                'state_id' => 5,
                'prison_name' => 'MSP Jama`are',
                'address' => '',
                'capacity' => '320',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 65,
                'state_id' => 5,
                'prison_name' => 'Alkaleri Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 66,
                'state_id' => 5,
                'prison_name' => 'Burra Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 67,
                'state_id' => 5,
                'prison_name' => 'Darazo Satellite',
                'address' => '',
                'capacity' => '30',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 68,
                'state_id' => 5,
                'prison_name' => 'Toro Satellite',
                'address' => '',
                'capacity' => '40',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 69,
                'state_id' => 5,
                'prison_name' => 'Gamawa Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 70,
                'state_id' => 5,
                'prison_name' => 'Shira Satellite',
                'address' => '',
                'capacity' => '20',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 71,
                'state_id' => 5,
                'prison_name' => "Tafawa \nBalewa Satellite",
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 72,
                'state_id' => 5,
                'prison_name' => 'Katagun Satellite',
                'address' => '',
                'capacity' => '30',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 73,
                'state_id' => 15,
                'prison_name' => 'Gombe',
                'address' => '',
                'capacity' => '379',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 74,
                'state_id' => 15,
                'prison_name' => 'Tula',
                'address' => '',
                'capacity' => '120',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 75,
                'state_id' => 15,
                'prison_name' => 'Cham Satellite',
                'address' => '',
                'capacity' => '60',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 76,
                'state_id' => 15,
                'prison_name' => 'Billiri Satellite',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 77,
                'state_id' => 15,
                'prison_name' => 'Bajoga Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 78,
                'state_id' => 2,
                'prison_name' => 'Yola Old',
                'address' => '',
                'capacity' => '596',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 79,
                'state_id' => 2,
                'prison_name' => 'Mubi',
                'address' => '',
                'capacity' => '400',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 80,
                'state_id' => 2,
                'prison_name' => 'Jimeta',
                'address' => '',
                'capacity' => '300',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 81,
                'state_id' => 2,
                'prison_name' => 'Numan',
                'address' => '',
                'capacity' => '400',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 82,
                'state_id' => 2,
                'prison_name' => 'Ganye',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 83,
                'state_id' => 2,
                'prison_name' => 'Jada',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 84,
                'state_id' => 2,
                'prison_name' => 'Michika Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 85,
                'state_id' => 2,
                'prison_name' => 'Gombi Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 86,
                'state_id' => 2,
                'prison_name' => 'Hong Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 87,
                'state_id' => 2,
                'prison_name' => 'Dumne Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 88,
                'state_id' => 2,
                'prison_name' => 'Guyuk Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 89,
                'state_id' => 2,
                'prison_name' => 'Kojoli Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 90,
                'state_id' => 2,
                'prison_name' => 'Mayobelwa Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 91,
                'state_id' => 2,
                'prison_name' => 'Shelleng Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 92,
                'state_id' => 2,
                'prison_name' => 'Maiha Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 93,
                'state_id' => 2,
                'prison_name' => 'Gulak Saterllite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 94,
                'state_id' => 2,
                'prison_name' => 'Karlahi Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 95,
                'state_id' => 8,
                'prison_name' => 'Bama',
                'address' => '',
                'capacity' => '320',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 96,
                'state_id' => 8,
                'prison_name' => 'Biu',
                'address' => '',
                'capacity' => '190',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 97,
                'state_id' => 8,
                'prison_name' => 'New Maiduguri',
                'address' => '',
                'capacity' => '800',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 98,
                'state_id' => 8,
                'prison_name' => 'Gwoza',
                'address' => '',
                'capacity' => '180',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 99,
                'state_id' => 8,
                'prison_name' => "Maiduguri \nFarm Centre",
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 100,
                'state_id' => 8,
                'prison_name' => "Maximum Security \nMaiduguri",
                'address' => '',
                'capacity' => '1900',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 101,
                'state_id' => 8,
                'prison_name' => "Mongono \nSatellite",
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 102,
                'state_id' => 8,
                'prison_name' => 'Kukawa Satellite',
                'address' => '',
                'capacity' => '70',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 103,
                'state_id' => 8,
                'prison_name' => "Gamboru-Ngala \nSatellite",
                'address' => '',
                'capacity' => '75',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 104,
                'state_id' => 8,
                'prison_name' => "Kumshe \nSatellite",
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 105,
                'state_id' => 8,
                'prison_name' => "Konduga \nSatellite",
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 106,
                'state_id' => 8,
                'prison_name' => "Damasak \nSatellite",
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 107,
                'state_id' => 8,
                'prison_name' => 'Askira Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 108,
                'state_id' => 8,
                'prison_name' => 'Shani Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 109,
                'state_id' => 8,
                'prison_name' => "Kwayakusar \nSatellite",
                'address' => '',
                'capacity' => '70',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 110,
                'state_id' => 34,
                'prison_name' => 'Jalingo',
                'address' => '',
                'capacity' => '250',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 111,
                'state_id' => 34,
                'prison_name' => 'New Wukari',
                'address' => '',
                'capacity' => '640',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 112,
                'state_id' => 34,
                'prison_name' => 'Serti',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 113,
                'state_id' => 34,
                'prison_name' => 'Gembu',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 114,
                'state_id' => 34,
                'prison_name' => 'Zing Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 115,
                'state_id' => 34,
                'prison_name' => 'Takum Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 116,
                'state_id' => 34,
                'prison_name' => 'Baissa Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 117,
                'state_id' => 34,
                'prison_name' => 'Bali Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 118,
                'state_id' => 34,
                'prison_name' => 'Lau Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 119,
                'state_id' => 34,
                'prison_name' => 'Gassol Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 120,
                'state_id' => 34,
                'prison_name' => 'M/Biyu Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 121,
                'state_id' => 34,
                'prison_name' => "Karin - Lamido \nSatellite",
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 122,
                'state_id' => 35,
                'prison_name' => 'Gashua',
                'address' => '',
                'capacity' => '104',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 123,
                'state_id' => 35,
                'prison_name' => 'Nguru',
                'address' => '',
                'capacity' => '93',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 124,
                'state_id' => 35,
                'prison_name' => 'MSP Potiskum',
                'address' => '',
                'capacity' => '416',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 125,
                'state_id' => 35,
                'prison_name' => 'Dapchi Satellite',
                'address' => '',
                'capacity' => '30',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 126,
                'state_id' => 35,
                'prison_name' => 'Damagun Satellite',
                'address' => '',
                'capacity' => '30',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 127,
                'state_id' => 35,
                'prison_name' => 'Geidam Satellite',
                'address' => '',
                'capacity' => '30',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 128,
                'state_id' => 35,
                'prison_name' => 'Damaturu Satellite',
                'address' => '',
                'capacity' => '30',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 129,
                'state_id' => 35,
                'prison_name' => 'Fika Satellite',
                'address' => '',
                'capacity' => '30',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 130,
                'state_id' => 26,
                'prison_name' => 'Agaie',
                'address' => '',
                'capacity' => '60',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 131,
                'state_id' => 26,
                'prison_name' => 'Bida',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 132,
                'state_id' => 26,
                'prison_name' => 'MSP Kotongora',
                'address' => '',
                'capacity' => '194',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 133,
                'state_id' => 26,
                'prison_name' => 'MSP Minna',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 134,
                'state_id' => 26,
                'prison_name' => 'Lapai',
                'address' => '',
                'capacity' => '62',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 135,
                'state_id' => 26,
                'prison_name' => 'Minna Old',
                'address' => '',
                'capacity' => '213',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 136,
                'state_id' => 26,
                'prison_name' => 'New - Bussa',
                'address' => '',
                'capacity' => '288',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 137,
                'state_id' => 26,
                'prison_name' => 'Kagara',
                'address' => '',
                'capacity' => '116',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 138,
                'state_id' => 23,
                'prison_name' => 'Ilorin',
                'address' => '',
                'capacity' => '121',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 139,
                'state_id' => 23,
                'prison_name' => 'Ilorin new/Mandala',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 140,
                'state_id' => 23,
                'prison_name' => 'Lafiaji',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 141,
                'state_id' => 23,
                'prison_name' => 'MSP Omu-Aran',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 142,
                'state_id' => 23,
                'prison_name' => 'Borstal',
                'address' => '',
                'capacity' => '250',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 143,
                'state_id' => 21,
                'prison_name' => 'Old Kebbi',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 144,
                'state_id' => 21,
                'prison_name' => 'New Kebbi',
                'address' => '',
                'capacity' => '240',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 145,
                'state_id' => 21,
                'prison_name' => 'Argungu',
                'address' => '',
                'capacity' => '180',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 146,
                'state_id' => 21,
                'prison_name' => 'Zuru',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 147,
                'state_id' => 21,
                'prison_name' => 'Yelwa Yauri',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 148,
                'state_id' => 21,
                'prison_name' => 'Kamba Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 149,
                'state_id' => 21,
                'prison_name' => 'Kangiwa Satellite',
                'address' => '',
                'capacity' => '146',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 150,
                'state_id' => 21,
                'prison_name' => 'Jega Satellite',
                'address' => '',
                'capacity' => '146',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 151,
                'state_id' => 21,
                'prison_name' => 'Bagundu Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 152,
                'state_id' => 21,
                'prison_name' => 'Wara Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 153,
                'state_id' => 36,
                'prison_name' => 'Gusau MSP',
                'address' => '',
                'capacity' => '1662',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 154,
                'state_id' => 36,
                'prison_name' => 'Talata Mafara Sat.',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 155,
                'state_id' => 36,
                'prison_name' => 'Maru Satellite',
                'address' => '',
                'capacity' => '60',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 156,
                'state_id' => 36,
                'prison_name' => 'Gumi Satellite',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 157,
                'state_id' => 36,
                'prison_name' => 'Kaura Namoda Sat.',
                'address' => '',
                'capacity' => '135',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 158,
                'state_id' => 33,
                'prison_name' => 'Sokoto',
                'address' => '',
                'capacity' => '884',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 159,
                'state_id' => 33,
                'prison_name' => 'Farm Centre Bissalam',
                'address' => '',
                'capacity' => '250',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 160,
                'state_id' => 33,
                'prison_name' => 'Gwadabawa Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 161,
                'state_id' => 33,
                'prison_name' => 'Wurno Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 162,
                'state_id' => 33,
                'prison_name' => 'Tambuwal Satellite',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 163,
                'state_id' => 37,
                'prison_name' => 'Suleja',
                'address' => '',
                'capacity' => '362',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 164,
                'state_id' => 37,
                'prison_name' => 'MSCC Kuje',
                'address' => '',
                'capacity' => '560',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 165,
                'state_id' => 37,
                'prison_name' => 'Dukpa Farm center',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 166,
                'state_id' => 1,
                'prison_name' => 'Aba',
                'address' => '',
                'capacity' => '542',
                'active' => 1,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 167,
                'state_id' => 1,
                'prison_name' => 'Umuahia',
                'address' => '',
                'capacity' => '500',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:10',
                'updated_at' => '2025-11-09 18:08:10',
            ],
            [
                'id' => 168,
                'state_id' => 1,
                'prison_name' => 'Arochukwu',
                'address' => '',
                'capacity' => '180',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 169,
                'state_id' => 3,
                'prison_name' => 'Abak',
                'address' => '',
                'capacity' => '',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 170,
                'state_id' => 3,
                'prison_name' => 'Eket',
                'address' => '',
                'capacity' => '123',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 171,
                'state_id' => 3,
                'prison_name' => 'Ikot-Abasi',
                'address' => '',
                'capacity' => '326',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 172,
                'state_id' => 3,
                'prison_name' => 'Ikot-Ekpene',
                'address' => '',
                'capacity' => '400',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 173,
                'state_id' => 3,
                'prison_name' => 'Uyo',
                'address' => '',
                'capacity' => '613',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 174,
                'state_id' => 16,
                'prison_name' => 'Owerri',
                'address' => '',
                'capacity' => '912',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 175,
                'state_id' => 16,
                'prison_name' => 'Okigwe',
                'address' => '',
                'capacity' => '504',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 176,
                'state_id' => 16,
                'prison_name' => 'Orreh Farm',
                'address' => '',
                'capacity' => '196',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 177,
                'state_id' => 9,
                'prison_name' => 'Adim Farm',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 178,
                'state_id' => 9,
                'prison_name' => 'Calabar',
                'address' => '',
                'capacity' => '450',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 179,
                'state_id' => 9,
                'prison_name' => 'Obubra',
                'address' => '',
                'capacity' => '127',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 180,
                'state_id' => 9,
                'prison_name' => 'Obudu',
                'address' => '',
                'capacity' => '49',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 181,
                'state_id' => 9,
                'prison_name' => 'Ogoja',
                'address' => '',
                'capacity' => '400',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 182,
                'state_id' => 9,
                'prison_name' => 'Ikom',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 183,
                'state_id' => 32,
                'prison_name' => 'Ahoada',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 184,
                'state_id' => 32,
                'prison_name' => 'Degema',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 185,
                'state_id' => 32,
                'prison_name' => 'Elele Farm',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 186,
                'state_id' => 32,
                'prison_name' => 'Max Sec.CC. Port-Harcourt',
                'address' => '',
                'capacity' => '1044',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 187,
                'state_id' => 6,
                'prison_name' => 'Okaka',
                'address' => '',
                'capacity' => '400',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 188,
                'state_id' => 30,
                'prison_name' => 'MSCC Agodi',
                'address' => '',
                'capacity' => '390',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 189,
                'state_id' => 30,
                'prison_name' => 'MSCC Oyo',
                'address' => '',
                'capacity' => '320',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 190,
                'state_id' => 30,
                'prison_name' => 'Ogbomoso Farm',
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 191,
                'state_id' => 29,
                'prison_name' => 'Ile-Ife',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 192,
                'state_id' => 29,
                'prison_name' => 'Ilesa',
                'address' => '',
                'capacity' => '586',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 193,
                'state_id' => 28,
                'prison_name' => 'MSCC Okitipupa',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 194,
                'state_id' => 28,
                'prison_name' => 'MSP-Ondo',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 195,
                'state_id' => 28,
                'prison_name' => 'MSCC Owo',
                'address' => '',
                'capacity' => '179',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 196,
                'state_id' => 28,
                'prison_name' => 'MSP Akure',
                'address' => '',
                'capacity' => '272',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 197,
                'state_id' => 28,
                'prison_name' => 'Female',
                'address' => '',
                'capacity' => '80',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 198,
                'state_id' => 13,
                'prison_name' => 'Ado-Ekiti',
                'address' => '',
                'capacity' => '650',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 199,
                'state_id' => 4,
                'prison_name' => 'Awka',
                'address' => '',
                'capacity' => '280',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 200,
                'state_id' => 4,
                'prison_name' => 'Onitsha',
                'address' => '',
                'capacity' => '600',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 201,
                'state_id' => 4,
                'prison_name' => 'MSP Nnewi',
                'address' => '',
                'capacity' => '',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 202,
                'state_id' => 4,
                'prison_name' => 'Nnewi ',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 203,
                'state_id' => 4,
                'prison_name' => 'Aguata',
                'address' => '',
                'capacity' => '210',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 206,
                'state_id' => 12,
                'prison_name' => 'Ogba Farm',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 207,
                'state_id' => 12,
                'prison_name' => 'Ozalla Farm',
                'address' => '',
                'capacity' => '496',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 208,
                'state_id' => 12,
                'prison_name' => 'Ubiaja',
                'address' => '',
                'capacity' => '140',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 209,
                'state_id' => 12,
                'prison_name' => 'Auchi',
                'address' => '',
                'capacity' => '140',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 210,
                'state_id' => 10,
                'prison_name' => 'Warri',
                'address' => '',
                'capacity' => '307',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 211,
                'state_id' => 10,
                'prison_name' => 'Ogwuashi-Uku',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 212,
                'state_id' => 10,
                'prison_name' => 'Sapele',
                'address' => '',
                'capacity' => '293',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 213,
                'state_id' => 10,
                'prison_name' => 'Agbor',
                'address' => '',
                'capacity' => '196',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 214,
                'state_id' => 10,
                'prison_name' => 'Kwale',
                'address' => '',
                'capacity' => '262',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 215,
                'state_id' => 11,
                'prison_name' => 'Abakaliki',
                'address' => '',
                'capacity' => '387',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 216,
                'state_id' => 11,
                'prison_name' => 'Afikpo',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 217,
                'state_id' => 14,
                'prison_name' => 'Max Sec CC Enugu',
                'address' => '',
                'capacity' => '1947',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 218,
                'state_id' => 14,
                'prison_name' => 'Ibite-Olo Farm',
                'address' => '',
                'capacity' => '250',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 219,
                'state_id' => 14,
                'prison_name' => 'Nsukka',
                'address' => '',
                'capacity' => '298',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 220,
                'state_id' => 14,
                'prison_name' => 'Oji River',
                'address' => '',
                'capacity' => '281',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 221,
                'state_id' => 7,
                'prison_name' => 'Gboko',
                'address' => '',
                'capacity' => '809',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 222,
                'state_id' => 7,
                'prison_name' => 'MSP Makurdi',
                'address' => '',
                'capacity' => '240',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 223,
                'state_id' => 7,
                'prison_name' => 'Otukpo',
                'address' => '',
                'capacity' => '298',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 224,
                'state_id' => 25,
                'prison_name' => 'Lafia',
                'address' => '',
                'capacity' => '300',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 225,
                'state_id' => 25,
                'prison_name' => 'Wamba',
                'address' => '',
                'capacity' => '68',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 226,
                'state_id' => 25,
                'prison_name' => 'MSP Keffi',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 227,
                'state_id' => 25,
                'prison_name' => 'Old keffi',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 228,
                'state_id' => 25,
                'prison_name' => 'Nassarawa',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 229,
                'state_id' => 31,
                'prison_name' => 'Max. Sec.CC Jos',
                'address' => '',
                'capacity' => '1149',
                'active' => 1,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 230,
                'state_id' => 31,
                'prison_name' => 'Jos ',
                'address' => '',
                'capacity' => '',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 231,
                'state_id' => 31,
                'prison_name' => 'Lamingo C. Camp',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 232,
                'state_id' => 31,
                'prison_name' => 'Lakushi Farm center',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 233,
                'state_id' => 31,
                'prison_name' => 'Pankshin',
                'address' => '',
                'capacity' => '161',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 234,
                'state_id' => 31,
                'prison_name' => 'Shedam',
                'address' => '',
                'capacity' => '220',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 235,
                'state_id' => 31,
                'prison_name' => 'Wase',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 236,
                'state_id' => 31,
                'prison_name' => 'Langtang',
                'address' => '',
                'capacity' => '150',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 237,
                'state_id' => 22,
                'prison_name' => 'Ankpa',
                'address' => '',
                'capacity' => '64',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 238,
                'state_id' => 22,
                'prison_name' => 'Dekina',
                'address' => '',
                'capacity' => '34',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 239,
                'state_id' => 22,
                'prison_name' => 'Idah',
                'address' => '',
                'capacity' => '102',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 240,
                'state_id' => 22,
                'prison_name' => 'Koton-Karfe',
                'address' => '',
                'capacity' => '302',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 241,
                'state_id' => 22,
                'prison_name' => 'Kabba',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 242,
                'state_id' => 22,
                'prison_name' => 'Okene',
                'address' => '',
                'capacity' => '160',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 243,
                'state_id' => 2,
                'prison_name' => 'Yola New',
                'address' => '',
                'capacity' => '',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 244,
                'state_id' => 5,
                'prison_name' => 'Bogoro',
                'address' => '',
                'capacity' => '96',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 245,
                'state_id' => 7,
                'prison_name' => 'Iga-Okapya FM',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 246,
                'state_id' => 7,
                'prison_name' => 'Jato AKA FC',
                'address' => '',
                'capacity' => '100',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 247,
                'state_id' => 12,
                'prison_name' => 'Auchi Female',
                'address' => '',
                'capacity' => '200',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 248,
                'state_id' => 17,
                'prison_name' => 'Babura',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 249,
                'state_id' => 18,
                'prison_name' => 'Kubacha',
                'address' => '',
                'capacity' => '96',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 250,
                'state_id' => 25,
                'prison_name' => 'Umashia F.C',
                'address' => '',
                'capacity' => '50',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
            [
                'id' => 251,
                'state_id' => 37,
                'prison_name' => 'Suleja New',
                'address' => '',
                'capacity' => '',
                'active' => 0,
                'status' => 1,
                'created_at' => '2025-11-09 18:08:11',
                'updated_at' => '2025-11-09 18:08:11',
            ],
        ]);

        DB::statement('ALTER TABLE prisons AUTO_INCREMENT = 252;');
    }
}
