<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('states')->insert([
            [
                'id' => 1,
                'state' => 'Abia',
                'capital' => 'Umuahia',
                'zone' => 'E',
                'zone_id' => 5,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:29',
                'updated_at' => '2025-11-09 18:52:29',
            ],
            [
                'id' => 2,
                'state' => 'Adamawa',
                'capital' => 'Yola',
                'zone' => 'Q',
                'zone_id' => 17,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:29',
                'updated_at' => '2025-11-09 18:52:29',
            ],
            [
                'id' => 3,
                'state' => 'Akwa Ibom',
                'capital' => 'Uyo',
                'zone' => 'O',
                'zone_id' => 15,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:29',
                'updated_at' => '2025-11-09 18:52:29',
            ],
            [
                'id' => 4,
                'state' => 'Anambra',
                'capital' => 'Awka',
                'zone' => 'M',
                'zone_id' => 13,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:29',
                'updated_at' => '2025-11-09 18:52:29',
            ],
            [
                'id' => 5,
                'state' => 'Bauchi',
                'capital' => 'Bauchi',
                'zone' => 'C',
                'zone_id' => 3,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:29',
                'updated_at' => '2025-11-09 18:52:29',
            ],
            [
                'id' => 6,
                'state' => 'Bayelsa',
                'capital' => 'Yenagoa',
                'zone' => 'I',
                'zone_id' => 9,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 7,
                'state' => 'Benue',
                'capital' => 'Makurdi',
                'zone' => 'H',
                'zone_id' => 8,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 8,
                'state' => 'Borno',
                'capital' => 'Maiduguri',
                'zone' => 'R',
                'zone_id' => 18,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 9,
                'state' => 'Cross River',
                'capital' => 'Calabar',
                'zone' => 'O',
                'zone_id' => 15,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 10,
                'state' => 'Delta',
                'capital' => 'Asaba',
                'zone' => 'G',
                'zone_id' => 7,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 11,
                'state' => 'Ebonyi',
                'capital' => 'Abakaliki',
                'zone' => 'M',
                'zone_id' => 13,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 12,
                'state' => 'Edo',
                'capital' => 'Benin City',
                'zone' => 'G',
                'zone_id' => 7,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 13,
                'state' => 'Ekiti',
                'capital' => 'Ado-Ekiti',
                'zone' => 'K',
                'zone_id' => 11,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 14,
                'state' => 'Enugu',
                'capital' => 'Enugu',
                'zone' => 'M',
                'zone_id' => 13,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 15,
                'state' => 'Gombe',
                'capital' => 'Gombe',
                'zone' => 'C',
                'zone_id' => 3,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 16,
                'state' => 'Imo',
                'capital' => 'Owerri',
                'zone' => 'E',
                'zone_id' => 5,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 17,
                'state' => 'Jigawa',
                'capital' => 'Dutse',
                'zone' => 'L',
                'zone_id' => 12,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 18,
                'state' => 'Kaduna',
                'capital' => 'Kaduna',
                'zone' => 'B',
                'zone_id' => 2,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 19,
                'state' => 'Kano',
                'capital' => 'Kano',
                'zone' => 'L',
                'zone_id' => 12,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 20,
                'state' => 'Katsina',
                'capital' => 'Katsina',
                'zone' => 'N',
                'zone_id' => 14,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 21,
                'state' => 'Kebbi',
                'capital' => 'Birnin Kebbi',
                'zone' => 'J',
                'zone_id' => 10,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 22,
                'state' => 'Kogi',
                'capital' => 'Lokoja',
                'zone' => 'H',
                'zone_id' => 8,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 23,
                'state' => 'Kwara',
                'capital' => 'Ilorin',
                'zone' => 'D',
                'zone_id' => 4,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 24,
                'state' => 'Lagos',
                'capital' => 'Ikeja',
                'zone' => 'A',
                'zone_id' => 1,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 25,
                'state' => 'Nasarawa',
                'capital' => 'Lafia',
                'zone' => 'P',
                'zone_id' => 16,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 26,
                'state' => 'Niger',
                'capital' => 'Minna',
                'zone' => 'D',
                'zone_id' => 4,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 27,
                'state' => 'Ogun',
                'capital' => 'Abeokuta',
                'zone' => 'A',
                'zone_id' => 1,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 28,
                'state' => 'Ondo',
                'capital' => 'Akure',
                'zone' => 'K',
                'zone_id' => 11,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 29,
                'state' => 'Osun',
                'capital' => 'Oshogbo',
                'zone' => 'F',
                'zone_id' => 6,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 30,
                'state' => 'Oyo',
                'capital' => 'Ibadan',
                'zone' => 'F',
                'zone_id' => 6,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 31,
                'state' => 'Plateau',
                'capital' => 'Jos',
                'zone' => 'P',
                'zone_id' => 16,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 32,
                'state' => 'Rivers',
                'capital' => 'Port Harcourt',
                'zone' => 'I',
                'zone_id' => 9,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 33,
                'state' => 'Sokoto',
                'capital' => 'Sokoto',
                'zone' => 'J',
                'zone_id' => 10,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 34,
                'state' => 'Taraba',
                'capital' => 'Jalingo',
                'zone' => 'Q',
                'zone_id' => 17,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 35,
                'state' => 'Yobe',
                'capital' => 'Damaturu',
                'zone' => 'R',
                'zone_id' => 18,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 36,
                'state' => 'Zamfara',
                'capital' => 'Gusau',
                'zone' => 'N',
                'zone_id' => 14,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
            [
                'id' => 37,
                'state' => 'F.C.T.',
                'capital' => 'Abuja',
                'zone' => 'B',
                'zone_id' => 2,
                'status' => 1,
                'created_at' => '2025-11-09 18:52:30',
                'updated_at' => '2025-11-09 18:52:30',
            ],
        ]);

        DB::statement('ALTER TABLE states AUTO_INCREMENT = 38;');
    }
}
